name: Upload PyPi Package with Poetry

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deploy_environment

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Python Poetry Action
      # You may pin to the exact commit or the version.
      uses: abatilo/actions-poetry@v2.1.3
      with:
        # The version of poetry to install
        poetry-version: "1.1.8"
    - name: Build package
      run: poetry build
    - name: Publish package
      env:
        # See https://python-poetry.org/docs/repositories/#configuring-credentials
        # See https://docs.github.com/en/actions/security-guides/encrypted-secrets#using-encrypted-secrets-in-a-workflow
        POETRY_PYPI_TOKEN_PYPI: ${{ secrets.POETRY_PYPI_TOKEN_PYPI }}
      run: |
        poetry build
        poetry publish
