# See https://docs.github.com/actions/automating-builds-and-tests/building-and-testing-nodejs-or-python?langId=py
name: Pytest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    # Right now this project only uses the standard library.
    # But at some point we might need to install dependencies.
    # Then we should probably look into making an action for installing poetry.
    # The requirements for this probject are not stored in a `requirements.txt` file.
    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install -r requirements.txt
    - name: Test with Pytest
      run: |
        pip install pytest
        pip install pytest-cov
        python3 -m pytest --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
